groblog_post:
    resource: "@GroblogBundle/Resources/config/routing/post.yml"
    prefix:   /post

groblog_homepage:
    path:     /
    defaults: { _controller: GroblogBundle:Default:index }

GroblogBundle_post:
    resource: "@GroblogBundle/Resources/config/routing/post.yml"
    prefix:   /post
