post:
    path:     /
    defaults: { _controller: "GroblogBundle:post:index" }

post_show:
    path:     /{id}/show
    defaults: { _controller: "GroblogBundle:post:show" }

post_new:
    path:     /new
    defaults: { _controller: "GroblogBundle:post:new" }

post_create:
    path:     /create
    defaults: { _controller: "GroblogBundle:post:create" }
    methods:  POST

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "GroblogBundle:post:edit" }

post_update:
    path:     /{id}/update
    defaults: { _controller: "GroblogBundle:post:update" }
    methods:  [POST, PUT]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "GroblogBundle:post:delete" }
    methods:  [POST, DELETE]
